; IMU Robotic Arm - ESP32 Receiver (Roboterseite)
; Board: ESP32-S3-WROOM-1-N16R8, Revision v1.0

[env:esp32s3-receiver]
platform                        = espressif32
board                           = esp32-s3-devkitc-1
framework                       = arduino

board_upload.flash_size         = 16MB
board_build.flash_mode          = qio
board_build.arduino.memory_type = qio_opi

monitor_speed                   = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
